import { createTheme } from "@nextui-org/react";

const lightTheme = createTheme({
  type: "light",
  theme: {
    colors: {
      textLight: "#363636",
      text: "#000000",
      linkLight: "#9A4EDD",
      link: "#5E1DAD",
      codeLight: "#B4B4B4",
      code: "#000000",
      selection: "#4ADE7B",
      border: "#4D4D4D",
      background: "#e1e1e1",
      backgroundAlpha: "rgba(255, 255, 255, 0.7)",
      foreground: "#000000",
      backgroundContrast: "#ececec",
      white: "#FFFFFF",
      black: "#000000",
      primaryLight: "#C4F3D6",
      primaryLightHover: "#A7EBBC",
      primaryLightActive: "#8AE2A2",
      primaryLightContrast: "#207D55",
      primary: "#4ADE7B",
      primaryBorder: "#207D55",
      primaryBorderHover: "#196842",
      primarySolidHover: "#125530",
      primarySolidContrast: "#ffffff",
      primaryShadow: "#207D55",
      secondaryLight: "#D6D4F4",
      secondaryLightHover: "#BAB8E8",
      secondaryLightActive: "#AFADE0",
      secondaryLightContrast: "#372E6C",
      secondary: "#6C63FF",
      secondaryBorder: "#372E6C",
      secondaryBorderHover: "#2B2359",
      secondarySolidHover: "#1E1946",
      secondarySolidContrast: "#ffffff",
      secondaryShadow: "#372E6C",
      neutralLight: "#E8E8E8",
      neutralLightHover: "#CCCCCC",
      neutralLightActive: "#BFBFBF",
      neutralLightContrast: "#3D3D3D",
      neutral: "#7F7F7F",
      neutralBorder: "#3D3D3D",
      neutralBorderHover: "#2E2E2E",
      neutralSolidHover: "#1F1F1F",
      neutralSolidContrast: "#ffffff",
      neutralShadow: "#3D3D3D",
      gradient:
        "linear-gradient(112deg, #DFE2E8 -25%, #F4CDDF -10%, #E6CEEB 80%)",
    },
    space: {},
    fonts: {},
  },
});

export default lightTheme;
