import { createTheme } from "@nextui-org/react";

const darkTheme = createTheme({
  type: "dark",
  theme: {
    colors: {
      textLight: "#E8E8E8",
      text: "#FFFFFF",
      linkLight: "#9A4EDD",
      link: "#5E1DAD",
      codeLight: "#B4B4B4",
      code: "#FFFFFF",
      selection: "#7dacf2",
      border: "#4D4D4D",
      background: "#262626",
      backgroundAlpha: "rgba(54, 54, 54, 0.7)",
      foreground: "#ECEDEE",
      backgroundContrast: "#363636",
      primaryLight: "#B8DAF9",
      primaryLightHover: "#9AC2F5",
      primaryLightActive: "#7DACF2",
      primaryLightContrast: "#204A7D",
      primary: "#1E90FF",
      primaryBorder: "#204A7D",
      primaryBorderHover: "#183E69",
      primarySolidHover: "#103153",
      primarySolidContrast: "#FFFFFF",
      primaryShadow: "#204A7D",
      secondaryLight: "#D6D4F4",
      secondaryLightHover: "#BAB8E8",
      secondaryLightActive: "#AFADE0",
      secondaryLightContrast: "#372E6C",
      secondary: "#6C63FF",
      secondaryBorder: "#372E6C",
      secondaryBorderHover: "#2B2359",
      secondarySolidHover: "#1E1946",
      secondarySolidContrast: "#ffffff",
      secondaryShadow: "#372E6C",
      neutralLight: "#E8E8E8",
      neutralLightHover: "#CCCCCC",
      neutralLightActive: "#BFBFBF",
      neutralLightContrast: "#3D3D3D",
      neutral: "#7F7F7F",
      neutralBorder: "#3D3D3D",
      neutralBorderHover: "#2E2E2E",
      neutralSolidHover: "#1F1F1F",
      neutralSolidContrast: "#ffffff",
      neutralShadow: "#3D3D3D",
      gradient:
        "linear-gradient(112deg, #61a2ff -25%, #5d71ff -10%, #7b57ff 80%)",
    },
    space: {},
    fonts: {},
  },
});

export default darkTheme;
